# Generated by Django 4.0.6 on 2023-09-30 10:37

from django.db import migrations, models
import home.custom_field


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feed_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hovaten', models.CharField(max_length=100)),
                ('tenchame', models.CharField(max_length=100)),
                ('diachi', models.CharField(max_length=100)),
                ('dienthoai', models.CharField(max_length=100)),
                ('gioitinh', models.CharField(max_length=100)),
                ('thoigian', models.TimeField()),
                ('ngay', models.DateField()),
                ('khoahoc', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name_plural': 'Feed'},
        ),
        migrations.AlterField(
            model_name='article',
            name='special',
            field=home.custom_field.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_homepage',
            field=home.custom_field.CustomBooleanField(),
        ),
    ]
